version: '2'
services:
  climbingzone4-app:
    image: climbingzone4
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://climbingzone4-mysql:3306/climbingzone4?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8081:8081
  climbingzone4-mysql:
    extends:
      file: mysql.yml
      service: climbingzone4-mysql
